# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayoutsExtents
                                 A QGIS plugin
 Saves the extents of all the maps from all the layouts inside a temporary layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-30
        copyright            : (C) 2025 by Baptiste PARIS
        email                : baptiste.paris.v@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayoutsExtents class from file LayoutsExtents.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layouts_extents import LayoutsExtents
    return LayoutsExtents(iface)
